export const metadata = {
  title: "BitRaise | CrowdFunding in Crypto",
  description: "Generated by create next app",
};

export const navItems = [
  {
    label: "About Us",
    href: "/about-us",
  },
  {
    label: "Vision",
    href: "/#vision",
  },
  {
    label: "How It Works",
    href: "/#how",
  },
];
